package com.mize.domain.util;

import java.io.Serializable;

public abstract class CatalogConstants implements Serializable{
	private static final long serialVersionUID = 1893011032395196052L;
	public static final String ENTITY_TYPE_COMPANY = "company";
	public static final String BUSINESS_ENTITY_TYPE = "BusinessEntityType";
	public static final String CUSTOMER_BUSINESS_ENTITY_TYPE = "CustomerBusinessEntityType";
	public static final String CURRENCY = "Currency";
	public static final String ADDRESS_TYPE = "AddressType";
	public static final String PHONE_TYPE = "PhoneType";
	public static final String BUSINESS_ENTITY_CONTACT_TYPE = "BusinessEntityContactType";
	public static final String BUSINESS_ENTITY_DEPARTMENT_TYPE = "BusinessEntityDepartmentType";
	public static final String SHIPPING_LOCATION_TYPE ="ShipLocationType";
	public static final String PURCHASE_ORDER_TYPE ="PurchaseOrderType";
	public static final String ORDER_RETURN_TYPE ="OrderReturnType";
	public static final String ORDER_IMPORT_TYPE ="OrderImportType";
	public static final String SHIPPING_METHOD ="ShippingMethod";
	public static final String SHIPPING_CARRIER ="ShippingCarrier";
	public static final String SHIPPING_PRIORITY ="ShippingPriority";
	public static final String PAYMENT_METHOD ="PaymentMethod";
	public static final String ENTITY_PARAMETER_TYPE ="EntityParameterType";
	public static final String ENTITY_ATTRIBUTE_TYPE = "EntityAttributeType";
	public static final String PURCHASE_ORDER_LOCATION_TYPE = "PurchaseOrderLocationType";
	public static final String PURCHASE_ORDER_STATUS = "OrderStatus";
	public static final String PART_KIT_TYPE ="PartKitType";
	public static final String PART_KIT_PRICE_METHOD ="PartKitPriceMethod";
	public static final String PART_UOM = "PartUOM";
	public static final String USER_ORGANIZATION_TYPE = "UserOrganizationType";
	public static final String SUBSTITUTE_CODE_TYPE ="SubstituteCodeType";
	public static final String PRICING_METHOD ="PricingMethod";
	public static final String HANDLING_CHARGE_PERCENT ="HandlingChargePercent";
	public static final String INVOICE_TYPE ="InvoiceType";
	public static final String PURCHASE_LOCATION_TYPE ="PurchaseLocationType";
	public static final String REGISTRATION_INDUSTRY_TYPE ="RegistrationIndustryType";
	public static final String REGISTRATION_CUSTOMER_TYPE ="RegistrationCustomerType";
	public static final String COVERAGE_TYPE = "CoverageType";
	public static final String PICK_LIST_TYPE = "PickListType";
	public static final String SHIPPING_DAYS = "ShippingDays";
	public static final String WQ_AUTHORIZATION_TYPE = "WQAuthorizationType";
	public static final String WQ_BUSINESS_ENTITY_TYPE = "WQBusinessEntityType";
	public static final String FORM_DEFENITION_STATUS = "FormDefinitionStatus";
	public static final String SERVICE_TYPE = "ServiceType";
	public static final String INSPECTION_TYPE = "InspectionType";
	public static final String INSPECTION_LOCATION_TYPE = "InspectionLocationType";
	public static final String PART_ATTRIBUTE_TYPE  = "PartAttributeType";
	public static final String PART_ATTRIBUTE_UOM  = "PartAttributeUOM";
	public static final String MESSAGE_TYPE = "MessageType";
	public static final String ENTITY_ORDER_TYPE = "EntityOrderType";
	public static final String REGION = "Region";
	public static final String LOCATOR_ENTITY_TYPE = "LocatorEntityType";
	public static final String MESSAGE_SEVERITY = "MessageSeverity";
	public static final String REASON_REQUIRED = "ReasonRequired";
	public static final String ORDER_REQUIRED = "OrderRequired";
	public static final String RETURN_WINDOW = "ReturnWindow";
	public static final String NON_RETURNABLE = "NonReturnable";
	public static final String ORDER_REQUEST_TYPE = "OrderRequestType";
	public static final String RETURN_REASON_TYPE = "ReturnReasonType";
	public static String RETURN_SHIP_TO_LOCATION_TYPE = "ReturnShipToLocationType";
	public static final String INVOICE_LOCATION_TYPE = "InvoiceLocationType";
	public static final String SHIP_LOCATION_TYPE = "ShipLocationType";
	public static final String LABOR_TYPE = "LaborType";
	public static final String PAGE_SIZE = "PageSize";
	public static final String CUSTOMER_SUB_TYPE ="CustomerSubType";
	public static final String PRODUCT_REGISTRATION_TYPE ="ProductRegistrationType";
	public static final String MANUFACTURER_TYPE = "ManufacturerType";
	public static final String PRODUCT_REGISTRATION_SOURCE = "ProductRegistrationSource";
	public static final String INSPAECTION_STATUS = "InspectionStatus";
}

